<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tester</title>
</head>



<body>
  <h1>Test your API!</h1>

  <!-- Testing the search -->
  <input type="text" placeholder="Search Pokemon here!" name="pokesearch"></input>

  <script>
    const testRoute = async (url) => {
      const response = await fetch(url)
      const data = await response.json()
      console.log('data:', data);
    }


    const url1 = `https://pokeapi.co/api/v2/pokemon/ditto`;

    testRoute(url1);

    //creating a fetch function for pokemon types and testing it
    const typeTest = () => {

      //defining a url variable which holds the url to a pokemon ground type database
      const urlGround = (`https://pokeapi.co/api/v2/type/5`);

      //returning a fetch promise
      return fetch(urlGround)
        //chaining .then promises 
        .then(response => {
          /*
          checking if the promise resolved, if not creating an error message to increase 
          error transparency to know how to debug (why it went wrong)
          */
          if (!response.ok) {
            throw new Error(`Error: ${response.status}`)
          }
          //when fetching from the given resource, the success default should be to return the response parsed with JSON
          return response.json();
          //taking the data or information within the response (information about ground types) and console logging all of ground type pokemon
        }).then(data => {
          console.log(data.pokemon)
          //returning it so the promise results in having a value to offer to another promise chained to this promise, if anything 
          return data.pokemon
        }).then(pokemon => {
          //returning a random pokemon of the ground type array by generating a number from 1 through 187 (representing the indexes of the object array the pokemon are held in)
          const randomNum = Math.ceil(Math.random() * 188)
          //returning the pokemon at the random given index generated by randomNum()
          console.log(pokemon[randomNum - 1])
        })
        //catching the error and throwing it back???
        .catch(error => {
          console.error('Could not fetch pokemon:', error);
          throw error; // Re-throw the error to ensure the promise is rejected?? I need more explanation 
        });


    }

    typeTest();






  </script>
</body>

</html>